name: pipeline

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
           fetch-depth: 1
           ref: main
           
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: yashu901
          password: ${{ secrets.DOCKERHUB}}
          
    - name: Build Docker image
      run: |
             docker build -t yashu901/pipe:latest .  

    - name: Push Docker image
      run: docker push yashu901/pipe:latest        

    - name: Test Docker image
      run: docker run --rm yashu901/pipe:latest echo "Container works!"

    - name: Run container on GitHub runner
      run: docker run -d -p 8080:80 yashu901/pipe:latest
